version: '3'

services:
  db:
    restart: always
    image: mysql
    container_name: monitoring_mysql
    ports:
      - 6603:3306
    environment:
      MYSQL_ROOT_PASSWORD: 'monitoring'
      MYSQL_DATABASE: 'monitoring'
    volumes:
      - monitoring_mysql_data:/var/lib/mysql

  web:
    restart: always
    depends_on:
      - db
    image: python:3
    container_name: monitoring_django
    volumes:
      - .:/www
    working_dir: /www
    env_file: .devenv
    environment:
      DEBUG: 'true'
    expose:
      - '8000'
    command: /bin/bash /www/scripts/initialize_django.sh
    links:
      - db:db

  nginx:
    restart: always
    container_name: monitoring_nginx
    build: ./.docker/nginx
    depends_on:
      - web
    links:
      - web:web
    volumes:
      - ./static:/www/static
    ports:
      - '8080:80'

volumes:
  monitoring_mysql_data:



